server:
  port: 8080

spring:
  application:
    name: crawler
  datasource:
    username: root
    password: 123456
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/crawler?serverTimezone=Asia/Shanghai&characterEncoding=utf8&useUnicode=true&useSSL=false&allowPublicKeyRetrieval=true
  mail:
    host: smtp.qq.com
    username: 1505127742@qq.com
    password: dzhiyxwhxgpjifda
    default-encoding: UTF-8



